products=[
    {
        "id": 1,
        "name": "Marks-Glover",
        "image": "http://dummyimage.com/107x100.png/5fa2dd/ffffff",
        "description": "Toxic effect of smoke, undetermined, initial encounter",
        "brand": "Kovacek-Botsford",
        "category": "HVAC",
        "price": "$7.71",
        "countInStock": 0,
        "rating": 5,
        "numReviews": 11
    },
    {
        "id": 10,
        "name": "Reynolds-Quigley",
        "image": "http://dummyimage.com/107x100.png/ff4444/ffffff",
        "description": "Other disorders of pancreatic internal secretion",
        "brand": "Swaniawski, Moore and Shanahan",
        "category": "Soft Flooring and Base",
        "price": "$4.46",
        "countInStock": 2,
        "rating": 3.5,
        "numReviews": 100
    },
    {
        "id": 31,
        "name": "Hilpert-Homenick",
        "image": "http://dummyimage.com/107x100.png/cc0000/ffffff",
        "description": "Disp fx of second metatarsal bone, r foot, init for opn fx",
        "brand": "Corwin-Pacocha",
        "category": "HVAC",
        "price": "$2.34",
        "countInStock": 3,
        "rating": 3.5,
        "numReviews": 88
    },
    {
        "id": 41,
        "name": "Macejkovic, Koelpin and Ryan",
        "image": "http://dummyimage.com/107x100.png/ff4444/ffffff",
        "description": "Complete lesion of L2 level of lumbar spinal cord",
        "brand": "Runolfsson, Padberg and Zieme",
        "category": "Wall Protection",
        "price": "$0.07",
        "countInStock": 4,
        "rating": 1,
        "numReviews": 90
    },
    {
        "id": 41,
        "name": "Marquardt, Ernser and McKenzie",
        "image": "http://dummyimage.com/107x100.png/cc0000/ffffff",
        "description": "Toxic effect of paints and dyes, NEC, accident1",
        "category": "Doors, Frames & Hardware",
        "price": "$0.82",
        "countInStock": 5,
        "rating": 4.5,
        "numReviews": 97
    },
    {
        "id": 51,
        "name": "Mayer and Sons",
        "image": "http://dummyimage.com/107x100.png/ff4444/ffffff",
        "description": "Nondisplaced transverse fracture of shaft of right ulna",
        "brand": "Dicki-Feeney",
        "category": "Curb & Gutter",
        "price": "$8.02",
        "countInStock": 6,
        "rating": 4,
        "numReviews": 20
    },
    {
        "id": 61,
        "name": "Mann-Armstrong",
        "image": "http://dummyimage.com/107x100.png/5fa2dd/ffffff",
        "description": "Nondisplaced dome fracture of unspecified talus, sequela",
        "brand": "Hoppe Inc",
        "category": "Ornamental Railings",
        "price": "$1.42",
        "countInStock": 7,
        "rating": 5,
        "numReviews": 99
    },
    {
        "id": 71,
        "name": "Nitzsche, Nader and Doyle",
        "image": "http://dummyimage.com/107x100.png/5fa2dd/ffffff",
        "description": "Nonrheumatic mitral valve disorder, unspecified",
        "brand": "Hayes Group",
        "category": "Painting & Vinyl Wall Covering",
        "price": "$0.66",
        "countInStock": 8,
        "rating": 3.5,
        "numReviews": 71
    },
    {
        "id": 81,
        "name": "Bergstrom-Green",
        "image": "http://dummyimage.com/107x100.png/5fa2dd/ffffff",
        "description": "Disp fx of lateral condyle of r tibia, 7thE",
        "brand": "Feeney, Mosciski and Reynolds",
        "category": "Electrical",
        "price": "$8.69",
        "countInStock": 9,
        "rating": 2.5,
        "numReviews": 29
    },
    {
        "id": 91,
        "name": "Harris Inc",
        "image": "http://dummyimage.com/107x100.png/5fa2dd/ffffff",
        "description": "Inj flexor musc/fasc/tend r rng fngr at wrs/hnd lv, sequela",
        "brand": "Hand-Jacobson",
        "category": "Structural & Misc Steel Erection",
        "price": "$3.58",
        "countInStock": 10,
        "rating": 1.5,
        "numReviews": 71
    },
    {
        "id": 441,
        "name": "Gutmann-Pollich",
        "image": "http://dummyimage.com/107x100.png/5fa2dd/ffffff",
        "description": "Nondisp fx of dist phalanx of l lit fngr, 7thD",
        "brand": "King and Sons",
        "category": "Marlite Panels (FED)",
        "price": "$7.19",
        "countInStock": 11,
        "rating": 1,
        "numReviews": 60
    },
    {
        "id": 661,
        "name": "Koss-Witting",
        "image": "http://dummyimage.com/107x100.png/5fa2dd/ffffff",
        "description": "Driver of pk-up/van inj in clsn w oth mv nontraf, sequela",
        "brand": "Lockman Group",
        "category": "HVAC",
        "price": "$0.89",
        "countInStock": 12,
        "rating": 4,
        "numReviews": 53
    },
    {
        "id": 561,
        "name": "Rodriguez, Carter and Bechtelar",
        "image": "http://dummyimage.com/107x100.png/5fa2dd/ffffff",
        "description": "Unspecified fracture of right calcaneus",
        "brand": "Pagac, Yost and Ruecker",
        "category": "Fire Protection",
        "price": "$7.50",
        "countInStock": 13,
        "rating": 3,
        "numReviews": 14
    },
    {
        "id": 3331,
        "name": "Hermiston-Parisian",
        "image":"http://dummyimage.com/107x100.png/5fa2dd/ffffff",
        "description": "Oth injury of unsp pulmonary blood vessels, subs encntr",
        "brand": "Kuvalis LLC",
        "category": "Casework",
        "price": "$2.64",
        "countInStock": 14,
        "rating": 4.5,
        "numReviews": 81
    },
    {
        "id": 34341,
        "image":"http://dummyimage.com/107x100.png/5fa2dd/ffffff",
        "name": "Considine17x100.png/dddddd/000000",
        "description": "Injury of unsp nerve at shldr/up arm, unsp arm, subs",
        "brand": "Green, Harvey and Ruecker",
        "category": "Termite Control",
        "price": "$0.46",
        "countInStock": 15,
        "rating": 2,
        "numReviews": 84
    }
]