export const USER_LOG_IN_SUCCESS= "USER_LOG_IN_SUCCESS"
export const USER_LOG_IN_FAILED= "USER_LOG_IN_FAILED"
export const USER_LOG_IN_REQUEST = "USER_LOG_IN_REQUEST"

export const USER_REGISTER_SUCCESS= "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILED= "USER_REGISTER_FAILED"
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"

export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAILED  = "USER_UPDATE_FAILED"
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_RESET = "USER_UPDATE_RESET"

export const USER_UPDATE_BY_ADMIN_SUCCESS = "USER_UPDATE_BY_ADMIN_SUCCESS"
export const USER_UPDATE_BY_ADMIN_FAILED  = "USER_UPDATE_BY_ADMIN_FAILED"
export const USER_UPDATE_BY_ADMIN_REQUEST = "USER_UPDATE_BY_ADMIN_REQUEST"
export const USER_UPDATE_BY_ADMIN_RESET = "USER_UPDATE_BY_ADMIN_RESET"


export const USER_DETAIL_BY_ID_REQUEST = "USER_DETAIL_BY_ID_REQUEST"
export const USER_DETAIL_BY_ID_FAILED = "USER_DETAIL_BY_ID_FAILED"
export const USER_DETAIL_BY_ID_SUCCESS = "USER_DETAIL_BY_ID_SUCCESS"
export const USER_DETAIL_BY_ID_RESET = "USER_DETAIL_BY_ID_RESET"


export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS"
export const USER_LIST_FAILED  = "USER_LIST_FAILED"
export const USER_LIST_REQUEST = "USER_LIST_REQUEST"
export const USER_LIST_RESET = "USER_LIST_RESET"


export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FAILED  = "USER_DELETE_FAILED"
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"

export const USER_REGISTER = "USER_REGISTER"
export const USER_LOG_OUT = "USER_LOG_OUT"


